In [1]:
import pandas as pd

file_path= "/scratch/akash/metadata/010d6dbb50674c8ed041b1e5f0a7896e.parquet"

df = pd.read_parquet(file_path, engine='pyarrow')

df["url"]

0         https://static.codepre.com/uploads/1595781771.png
1         https://lh4.ggpht.com/9mX9NrvDxMjnWbtkxLat8o2b...
2         https://m.media-amazon.com/images/I/71Zi0pNi44...
3         https://ae04.alicdn.com/kf/H9aca05330fbc49a6ba...
4         https://www.newsline-media.com/img-get2/I0000i...
                                ...
528797    https://clipartart.com/images/free-clipart-of-...
528798    https://www.ibraggiotti.com//media/catalog/pro...
528799    https://www.livingspaces.com/api/image?recId=1...
528800    https://i.pinimg.com/236x/0d/ea/77/0dea776bb49...
528801    http://i00.i.aliimg.com/photo/v1/60006493826/T...
Name: url, Length: 528802, dtype: object

In [3]:
df.head()

,uid,url,text,original_width,original_height,clip_b32_similarity_score,clip_l14_similarity_score,face_bboxes,sha256
0,64748b36e8c6a0e126164407a4911fc8,https://static.codepre.com/uploads/1595781771.png,Install and configure October CMS on CentOS 8,1024,583,0.263672,0.247559,[],c84253691515429f1b7ff455c7bb3bb3204287044dd740...
1,9f2704fa536065648963583b039f20be,https://lh4.ggpht.com/9mX9NrvDxMjnWbtkxLat8o2b...,Slots Paradise™ - screenshot thumbnail,174,310,0.318359,0.269775,"[[0.5823844075202942, 0.4352933466434479, 0.88...",026973a67430fce8192eccac7ce370e99e33a98007aa7d...
2,c779d31c7a2256df8bc7f0aa73f2988a,https://m.media-amazon.com/images/I/71Zi0pNi44...,White HeadbandWhite Baptism HeadbandChristenin...,1500,1166,0.291992,0.258301,"[[0.06728982925415039, 0.625583291053772, 0.08...",b0db19240ab12e4906ed8ce29a8cbedfec83315b4acd2c...
3,8b737904edd0d8a8bd41b6482fac686e,https://ae04.alicdn.com/kf/H9aca05330fbc49a6ba...,usb 3 0 to sata dual bay hard drive dock exter...,200,200,0.317383,0.263428,[],db25aa6e3854846c9d400cc63eca8455e1173e58316006...
4,c859b9bd5c505f46e3895c3d2a44ad13,https://www.newsline-media.com/img-get2/I0000i...,"DUNDEE, SCOTLAND, APRIL 2021: An increase in t...",180,120,0.315186,0.303711,[],34283e8d994e3b3b4991a2de9cd83e1f05b459aa1faf6f...

In [8]:
import glob
import pandas as pd
csv_file_path= "/scratch/akash/metadata"
csv_files= glob.glob(csv_file_path+"/*.csv")

print(len(csv_files))
total_count= 0
high_sim_count= 0
for file in csv_files:
    df= pd.read_csv(file, engine="python", on_bad_lines="skip")
    # Convert the similarity score column to numeric, coercing non-numeric to NaN
    df["clip_b32_similarity_score"] = pd.to_numeric(df["clip_b32_similarity_score"], errors="coerce")
    df_high_sim= df[df["clip_b32_similarity_score"]>0.28]
    total_count+= len(df)
    high_sim_count+= len(df_high_sim)

print(total_count)
print(high_sim_count)

2664
45152307
37980847

In [6]:
df

,text,clip_b32_similarity_score,clip_l14_similarity_score
0,TEIN Street Basis Coilovers 89-91 HONDA CIVIC ...,0.349365,0.326172
1,Lark Lane will host the festival,0.329590,0.273682
2,The conflict over putting in a hard-rock mine ...,0.294189,0.246948
3,Urban Decay Naked Heat Palette,0.314453,0.291260
4,Inside Urban Green Card LED Desk Lamp From Tos...,0.334961,0.286865
...,...,...,...
17143,"Marigolds flowers and blue sky in garden ,Thai...",0.321289,0.294678
17144,Nuna Pipa nuna pipa infant car seat jett,0.327637,0.281738
17145,Not A Time Machine - Bumper Sticker Car Bumper...,0.413086,0.356689
17146,PES 2017 Faces Donny van de Beek by Sameh Momen,0.389160,0.403809
17147,© Licensed to London News Pictures. 01/01/2018...,0.296387,0.250488

In [7]:
import timm
# vit_huge_models = timm.list_models('*vit*huge*', pretrained=True)
# model = timm.create_model('vit_huge_patch14_224_in21k', pretrained=True)

['vit_huge_patch14_224_clip_laion2b', 'vit_huge_patch14_224_in21k']

In [6]:
import pandas as pd

file_path= "/scratch/akash/shards/00000007.parquet"

df = pd.read_parquet(file_path, engine='pyarrow')
df.head()

,uid,caption,url,key,status,error_message,width,height,original_width,original_height,exif,sha256
0,613c4c8bcf687e5f28416e45c0f7e8b9,Strength of a Woman Dog T-Shirt,http://i3.cpcache.com/product/1116256041/stren...,000000070016,failed_to_download,<urlopen error [Errno -2] Name or service not ...,NaN,NaN,NaN,NaN,None,None
1,f5225c983d2d52479700b4f682887037,leather sofa cleaner tips for cleaning leather...,http://tse4.mm.bing.net/th?id=OIP.n0R2yy8dffqL...,000000070019,success,None,474.0,355.0,474.0,355.0,"{""Image ExifOffset"": ""26"", ""EXIF Tag 0x4000"": ...",384fe258eb0731f182e656f79697c20826608f074ad607...
2,c34530f6ea8936ef7bd7f1de29009582,Download The 2005 Economic and Product Market ...,https://images-na.ssl-images-amazon.com/images...,000000070007,success,None,387.0,500.0,387.0,500.0,{},f8ed6b46563e69950f0fe5c62bd258fb83e32c3908fd49...
3,1a3355fa992d57bf5bbe2a39e7410e10,Thunder Acres Premium Alfalfa Hay for Pets,https://m.media-amazon.com/images/I/61lXk9SoWA...,000000070003,success,None,500.0,334.0,500.0,334.0,{},3359cc41d2813f11aa12ccee44a41c9401dc2636417c99...
4,c0a1598bb8745fea25cdbcb232d56554,Super Dog! - Stock Vector,http://static4.depositphotos.com/1030387/398/v...,000000070012,success,None,150.0,150.0,150.0,150.0,{},636e4da0e525937be926e7b14109debc8dca7c610057cd...